### ISSUE TITLE
Add random join/leave messages when user connect to chat.

### ISSUE THREAD

**Issue by LWJerri** [lucasmrl/chat-app#12]

**Comment by lucasmrl** [comment]
@LWJerri That one is easy. Do you have any phrases on your mind?

**Comment by LWJerri** [comment]
> @LWJerri That one is easy. Do you have any phrases on your mind?

No(

**Comment by lucasmrl** [comment]
> > @LWJerri That one is easy. Do you have any phrases on your mind?
> 
> No(

What about:
"YAY, the great username joined the chat! 😎"
"Welcome username!😃"
"Everyone, username is here! 🎉"
"Wow, look who joined us! username is here to stay! 🤩"

**Comment by LWJerri** [comment]
> > > @LWJerri That one is easy. Do you have any phrases on your mind?
> > 
> > 
> > No(
> 
> What about:
> "YAY, the great username joined the chat! 😎"
> "Welcome username!😃"
> "Everyone, username is here! 🎉"
> "Wow, look who joined us! username is here to stay! 🤩"

Yeah, for start you can add this.
