### ISSUE TITLE
Void messages

### ISSUE THREAD

**Issue by LWJerri** [lucasmrl/chat-app#3]
I can send void messages.
![Screenshot_2021-01-09-20-59-55-591](https://user-images.githubusercontent.com/50290430/104106373-d6bded80-52bd-11eb-9ebe-27b0e4627093.jpeg)

**Comment by lucasmrl** [comment]
Fixed.
Now, when the user tries to send an empty message, it will show up a toast (react-hot-toast) asking the user to type something.

Thank you! :)
