### ISSUE TITLE
Chat not set on full screen.

### ISSUE THREAD

**Issue by LWJerri** [lucasmrl/chat-app#5]
Can you make responsible chat on all screen size?

System:
![Screenshot_2021-01-10-00-58-30-110](https://user-images.githubusercontent.com/50290430/104110289-fca7ba00-52de-11eb-8380-f508c3960a4e.jpeg)

Bug:
![Screenshot_2021-01-10-00-57-34-605](https://user-images.githubusercontent.com/50290430/104110270-d5e98380-52de-11eb-8bdd-e1b63d3d8fb0.jpeg)

**Comment by lucasmrl** [comment]
Definitely. I just focused on mobile and desktop but missed for iPad and similar screen sizes.

**Comment by lucasmrl** [comment]
Fixed
