### ISSUE TITLE
User with `null` nickname

### ISSUE THREAD

**Issue by LWJerri** [lucasmrl/chat-app#7]
Sometimes I show messages **null left the chat 👋🏻**. Can you fix it?

![image](https://user-images.githubusercontent.com/50290430/104111361-9ffdcc80-52e9-11eb-89d0-ab5ecabff10c.png)

**Comment by lucasmrl** [comment]
Note to myself:
Only show welcome/goodbye message after user have a nickname.

**Comment by lucasmrl** [comment]
Fixed!
